# This file is a template, and might need editing before it works on your project.
image: golang:latest

variables:
  REPO_NAME: github.com/xsolla/login-sdk-go
  GIT_SSL_NO_VERIFY: "true"

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab model
# is gitlab.com, and that your repository is namespace/project, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/gitlab.com/namespace/project
# Thus, making a symbolic link corrects this.
before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - lint
  - test
  - build
  - release

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

lint:
  image: golangci/golangci-lint:v1.44.2
  stage: lint
  script:
    - golangci-lint run -v

compile:
  stage: build
  script:
    - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/mybinary
  artifacts:
    paths:
      - mybinary

release:
  image: node:14-buster-slim
  stage: release
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
  script:
    - npm ci && npm run semantic-release
  only:
    refs:
      - master
      - beta
      - alpha
    variables:
      - $CI_COMMIT_MESSAGE !~ /skip release/